try {
    throw "error";

} catch (err) {
    console.log(err);
    console.log(err);
    // return res.send("some error occouring : ");
}